const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image1: '/assets/images/productImage/p1.jpg',
            image2: '/assets/images/productImage/p2.jpg',
            image3: '/assets/images/productImage/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image1: '/assets/images/productImage/p2.jpg',
            image2: '/assets/images/productImage/p2.jpg',
            image3: '/assets/images/productImage/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image1: '/assets/images/productImage/p3.jpg',
            image2: '/assets/images/productImage/p3.jpg',
            image3: '/assets/images/productImage/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image1: '/assets/images/productImage/p4.jpg',
            image2: '/assets/images/productImage/p4.jpg',
            image3: '/assets/images/productImage/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image1: '/assets/images/productImage/p5.jpg',
            image2: '/assets/images/productImage/p5.jpg',
            image3: '/assets/images/productImage/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Fit Pant6',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Adidas Fit Pant1',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Adidas Fit Pant2',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '9',
            name: 'Adidas Fit Pant3',
            category: 'Pants',
            image1: '/assets/images/productImage/p6.jpg',
            image2: '/assets/images/productImage/p6.jpg',
            image3: '/assets/images/productImage/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
    songs: [
        {
            name: 'Song',
            singer: 'NightCore',
            path: '/assets/music/song1.mp3',
            img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZYXSNeSWixiBDeSKVOHlwUfhW6g-BwfKiDg&usqp=CAU',
        },
        {
            name: 'Song1',
            singer: 'NightCore1',
            path: 'https://webshop1-app.onrender.com/assets/music/song2.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/92215197_p0_master1200.jpg',
        },
        {
            name: 'Song2',
            singer: 'NightCore2',
            path: 'https://webshop1-app.onrender.com/assets/music/song3.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/94755985_p0_master1200.jpg',
        },
        {
            name: 'Song3',
            singer: 'NightCore3',
            path: 'https://webshop1-app.onrender.com/assets/music/song4.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/95664953_p0_master1200.jpg',
        },
        {
            name: 'Song4',
            singer: 'NightCore4',
            path: 'https://webshop1-app.onrender.com/assets/music/song5.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/95680161_p0_master1200.jpg',
        },
        {
            name: 'Song5',
            singer: 'NightCore5',
            path: 'https://webshop1-app.onrender.com/assets/music/song6.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/95819670_p0_master1200.jpg',
        },
        {
            name: 'Song6',
            singer: 'NightCore6',
            path: 'https://webshop1-app.onrender.com/assets/music/song7.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/96114072_p0_master1200.jpg',
        },
        {
            name: 'Song7',
            singer: 'NightCore7',
            path: 'https://webshop1-app.onrender.com/assets/music/song8.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/89455468_p0_master1200.jpg',
        },
        {
            name: 'Song8',
            singer: 'NightCore8',
            path: 'https://webshop1-app.onrender.com/assets/music/song9.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/94632192_p0_master1200.jpg',
        },
        {
            name: 'Song9',
            singer: 'NightCore9',
            path: 'https://webshop1-app.onrender.com/assets/music/song10.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/93231708_p0_master1200.jpg',
        },
        {
            name: 'Song10',
            singer: 'NightCore10',
            path: 'https://webshop1-app.onrender.com/assets/music/song11.mp3',
            img: 'https://webshop1-app.onrender.com/assets/img/88956271_p0_master1200.jpg',
        },
    ],
};
export default data;
